name = "UnitfulAstro"
uuid = "6112ee07-acf9-5e0f-b108-d242c714bf9f"
license = "MIT"
version = "0.4.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAngles = "6fb2a4bd-7999-5318-a3b2-8ad61056cd98"

[compat]
Unitful = "≥ 0.17.0"
julia = "≥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
